set(PYCICLE_GITHUB_PROJECT_NAME  "hpx")
set(PYCICLE_GITHUB_ORGANISATION  "STEllAR-GROUP")
set(PYCICLE_GITHUB_MASTER_BRANCH "master")
set(PYCICLE_CDASH_SERVER_NAME    "hpx")
set(PYCICLE_CTEST_BUILD_TARGET   "tests")

